INSERT INTO categoria(nombre, foto) VALUES ('Bebidas', 'https://grupo1-proyecto.s3.sa-east-1.amazonaws.com/categorias/alcohol.jpeg');
INSERT INTO categoria(nombre, foto) VALUES ('Comida oriental', 'https://grupo1-proyecto.s3.sa-east-1.amazonaws.com/categorias/china.jpg');
INSERT INTO categoria(nombre, foto) VALUES ('Chivitos', 'https://grupo1-proyecto.s3.sa-east-1.amazonaws.com/categorias/chivitos.jpg');
INSERT INTO categoria(nombre, foto) VALUES ('Empanadas', 'https://grupo1-proyecto.s3.sa-east-1.amazonaws.com/categorias/empanadas.jpg');
INSERT INTO categoria(nombre, foto) VALUES ('Comida española', 'https://grupo1-proyecto.s3.sa-east-1.amazonaws.com/categorias/espanola.jpg');
INSERT INTO categoria(nombre, foto) VALUES ('Hamburguesas', 'https://grupo1-proyecto.s3.sa-east-1.amazonaws.com/categorias/hamburguesa.jpg');
INSERT INTO categoria(nombre, foto) VALUES ('Helados', 'https://grupo1-proyecto.s3.sa-east-1.amazonaws.com/categorias/helado.jpg');
INSERT INTO categoria(nombre, foto) VALUES ('Comida italiana', 'https://grupo1-proyecto.s3.sa-east-1.amazonaws.com/categorias/italiana.jpg');
INSERT INTO categoria(nombre, foto) VALUES ('Desayunos y Meriendas', 'https://grupo1-proyecto.s3.sa-east-1.amazonaws.com/categorias/meriendas.jpg');
INSERT INTO categoria(nombre, foto) VALUES ('Comida mexicana', 'https://grupo1-proyecto.s3.sa-east-1.amazonaws.com/categorias/mexicana.jpg');
INSERT INTO categoria(nombre, foto) VALUES ('Milanesas', 'https://grupo1-proyecto.s3.sa-east-1.amazonaws.com/categorias/milanesa.jpg');
INSERT INTO categoria(nombre, foto) VALUES ('Parrillada', 'https://grupo1-proyecto.s3.sa-east-1.amazonaws.com/categorias/parrilla.jpg');
INSERT INTO categoria(nombre, foto) VALUES ('Pasta', 'https://grupo1-proyecto.s3.sa-east-1.amazonaws.com/categorias/pasta.jpg');
INSERT INTO categoria(nombre, foto) VALUES ('Pastelería', 'https://grupo1-proyecto.s3.sa-east-1.amazonaws.com/categorias/pasteleria.jpg');
INSERT INTO categoria(nombre, foto) VALUES ('Picadas', 'https://grupo1-proyecto.s3.sa-east-1.amazonaws.com/categorias/picadas.jpg');
INSERT INTO categoria(nombre, foto) VALUES ('Pizzas', 'https://grupo1-proyecto.s3.sa-east-1.amazonaws.com/categorias/pizzas.jpg');
INSERT INTO categoria(nombre, foto) VALUES ('Postres', 'https://grupo1-proyecto.s3.sa-east-1.amazonaws.com/categorias/postre.jpg');
INSERT INTO categoria(nombre, foto) VALUES ('Saludable', 'https://grupo1-proyecto.s3.sa-east-1.amazonaws.com/categorias/saludable.jpg');
INSERT INTO categoria(nombre, foto) VALUES ('Comida vegana', 'https://grupo1-proyecto.s3.sa-east-1.amazonaws.com/categorias/vegano.jpg');
INSERT INTO categoria(nombre, foto) VALUES ('Comida vegetariana', 'https://grupo1-proyecto.s3.sa-east-1.amazonaws.com/categorias/vegetariano.jpg');
